sudo: required
dist: trusty
cache: bundler
language: ruby
rvm:
  - 2.3.1
before_install:
  - mysql -e 'SET PASSWORD FOR "root"@"localhost" = PASSWORD("");' -uroot
env:
  matrix:
    - SOLIDUS_BRANCH=master DB=mysql
